Adjusted package module inventory to include quotes around fields when needed
On FreeBSD where package versions can have commas such as joe-4.6,1 this was causing errors with the use of packagesmatching() function.

```
   error: Line from package inventory 'joe,4.6,1,amd64,pkg' did not yield correct number of elements.
```

Used CsvWriterField to quote the field in case it includes " , \r \n. See CsvWriterField() at https://github.com/NorthernTechHQ/libntech/blob/master/libutils/csv_writer.c#L73

Had to add a workaround to convert CRLF written by csv_writer to expected LF in resulting inventory_list.

Ticket: CFE-4341
Changelog: title

Co-authored-by: Lars Erik Wik <lars.erik.wik@northern.tech>