cf-upgrade: Fix out of tree builds
Building cfengine core out of the source tree fails with this error:

Making all in cf-upgrade
  CC       process.o
../../../../cf-upgrade/process.c:25:22: fatal error:
 platform.h: No such file or directory
 #include <platform.h>
                      ^
compilation terminated.
Makefile:513: recipe for target 'process.o' failed

After adding the missing include path to CPPFLAGS, the build
finishes successfully.

Signed-off-by: Stefan Weil <sw@weilnetz.de>