Redmine #7455: Fix build with musl libc.
Check for each header with AC_HEADER_CHECK instead assuming that needed
headers only exist on GNU libc and bionic.

This fixes the following build error when building on linux with musl libc:
In file included from ../libutils/platform.h:358:0,
                 from generic_at.c:25:
/usr/include/linux/if.h:71:2: error: expected identifier before numeric
constant
  IFF_UP    = 1<<0,  /* sysfs */
  ^
In file included from /usr/include/linux/route.h:26:0,
                 from ../libutils/platform.h:378,
                 from generic_at.c:25:
/usr/include/linux/if.h:169:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^

Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>

Changelog: Title