Zero bytes in class guards no longer cause crashes
A varclass is a class guard which uses quotes, like:

```
"$(myvariable)"::
```

(Or similar with single quotes). Previously, the parser
allowed zero bytes inside those quotes, but crashed when trying
to store the class guard string. This fix causes zero bytes to
correctly give errors instead of crashing.

```
 verbose: BEGIN parsing file: /northern.tech/cfengine/test.cf
/northern.tech/cfengine/test.cf:3:44: error: Runaway string
' reports:
                                           ^
/northern.tech/cfengine/test.cf:3:44: error: syntax error
' reports:
                                           ^
/northern.tech/cfengine/test.cf:3:44: error: Expected 'bundle' or 'body' keyword, wrong input '' reports:
'
' reports:
                                           ^
 verbose: END   parsing file: /northern.tech/cfengine/test.cf
   error: There are syntax errors in policy files
```

(The error message could be better, but this should never happen,
except for fuzzed input or malicious input).

Changelog: Title
Ticket: CFE-3028
Signed-off-by: Ole Herman Schumacher Elgesem <ole@northern.tech>
(cherry picked from commit 9580ee3089e62cb3e169de954a33b6f0a939db95)