CFE-2960: copylink_pattern honor '/../' in copy source
When source containt `<path>/../<file>`, eg:
 * `/tmp/source/../templates/group`

copylink_pattern failed with:
```
 error: Can't stat '/tmp/source/templates' in ExpandLinks. (lstat: No such file or directory)
```

Changelog: Title
(cherry picked from commit ce831f95dfb672708c55f97ead7e90ed201411c5)