Fixed failure to install cf-remote
```
error: externally-managed-environment
```

Since this is a container, it should be OK to potentially break system
packages.

Ticket: None
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>