Undo the uber-hack of redefining DIST_COMMON
It fixes error messages while compiling tarball:

error: required file './compile' not found
(cherry picked from commit e16fa275b149621d23294ba325d55f5f610d2894)