Fixed deprecated-non-prototype compiler warnings
error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype

with clang 14.0.3 on MacOS

Ticket: ENT-9878
Changelog: title
(cherry picked from commit 4d66859eaff3895a3ed08283c8498b7fc83a1922)